[package]
name = "adventofcode2025"
version = "0.1.0"
edition = "2024"

[dependencies]
geo = "0.32.0"
good_lp = { version = "1.14.2", default-features = false, features = [ "highs" ] }
nalgebra = "0.34.1"
